services:
   namenode:
      image: apache/hadoop:3.5.0
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - "9870:9870"
        - "8020:8020"
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"

   datanode:
      image: apache/hadoop:3.5.0
      command: ["hdfs", "datanode"]
      env_file:
        - ./config      
      deploy:
        replicas: 3  

   jupyter:
      build:
        context: .
        dockerfile: Dockerfile.jupyter
      hostname: jupyter
      working_dir: /app
      command: start-notebook.py --IdentityProvider.token='' --ServerApp.password=''
      ports:
        - "8888:8888"
      volumes:
        - ./datasets:/app/datasets
        - ./notebooks:/app/notebooks
      environment:
        - JUPYTER_ENABLE_LAB=yes
      depends_on:
        - namenode

